apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: thymeleaf
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
         app: test
    spec:
      imagePullSecrets:
         - name: github-secret
      containers:
         - name: test
           image: localhost:5000/host_go:latest
           ports:
              - containerPort: 8080
           env:
             - name: SPRING_DATASOURCE_URL
               value: "jdbc:postgresql://postgres-service:5432/hostGo"
             - name: SPRING_DATASOURCE_USERNAME
               value: "postgres"
             - name: SPRING_DATASOURCE_PASSWORD
               value: "1234567890"
             - name: SPRING_JPA_HIBERNATE_DDL_AUTO
               value: "update"
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: thymeleaf
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080